version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: im
      POSTGRES_PASSWORD: im
      POSTGRES_DB: im
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  gateway:
    build: ./services/gateway
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis://redis:6379
      AUTH_SERVICE_URL: http://messages:3000
    depends_on:
      - redis
      - messages
  messages:
    build: ./services/messages
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://im:im@postgres:5432/im
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
volumes:
  pgdata:
